@Gtest_HostAddress = http://localhost:9091

POST {{Gtest_HostAddress}}/server/api/gwp
Content-Type: application/json
Accept: application/json

{
  "country": "cz",
  "lob": [ "transport", "liability" ]
}

###
